services:
  - type: web
    name: kodrotasi
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /api/v1/projects
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: JDBC_DATABASE_URL
        sync: false
      - key: DATABASE_USERNAME
        sync: false
      - key: DATABASE_PASSWORD
        sync: false
      - key: JWT_SECRET
        generateValue: true

